require("ricdotnet.lazy")
require("ricdotnet.lsp")
require("ricdotnet.git")
require("ricdotnet.icons")
require("ricdotnet.theme")
require("ricdotnet.statusline")
require("ricdotnet.set")
require("ricdotnet.keys")
